export enum APP_ACTIONS {
  UPDATE_SEARCH_TEXT = "UPDATE_SEARCH_TEXT",
  USER_ENTRY_MENU_CLICKED = "USER_ENTRY_MENU_CLICKED",
  USER_ENTRY_COMPLETED = "USER_ENTRY_COMPLETED",
  LOGOUT = "LOGOUT",
  LOGIN = "LOGIN",
  REGISTER_USER_INFO = "REGISTER_USER_INFO",
}

export enum DASHBOARD_ACTIONS {
  GET_ALL_BOOKS = "GET_ALL_BOOKS",
  SET_ALL_BOOKS = "SET_ALL_BOOKS",
  FILTER_BOOKS = "FILTER_BOOKS",
  SORT_FILTER = "SORT_FILTER",
}

export enum USER_ENTRY_ACTIONS {
  SET_TITLE = "SET_TITLE",
  SET_USER_ENTRY_STATE = "SET_USER_ENTRY_STATE",
}
