export enum APP_ACTIONS {
  UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT',
}

export enum DASHBOARD_ACTIONS {
  GET_ALL_BOOKS = 'GET_ALL_BOOKS',
  SET_ALL_BOOKS = 'SET_ALL_BOOKS',
  SEARCH_BOOKS = 'SEARCH_BOOKS',
  APPLY_FILTER = 'APPLY_FILTER',
  CLEAR_FILTER = 'CLEAR_FILTER',
  SORT_ACTION = 'SORT_ACTION',
  UPDATE_DASHBOARD_SCROLL = 'UPDATE_DASHBOARD_SCROLL',
}

export enum USER_ENTRY_ACTIONS {
  SET_TITLE = 'SET_TITLE',
  SET_USER_ENTRY_STATE = 'SET_USER_ENTRY_STATE',
}

export enum CART_ACTIONS {
  UPDATE_QTY = 'UPDATE_QTY',
  SET_PAYABLE_AMOUNT = 'SET_PAYABLE_AMOUNT',
}
